### ISSUE TITLE
test 7 ft_memchr

### ISSUE THREAD

**Issue by TheoVideira** [SimplySka/libft-war-machine-v2019#1]
test 7 for ft_memchr always aborts. Even when i replace ft_memchr by memchr it aborts. Parameter "size_t n" may be too long

**Comment by SimplySka** [comment]
Don’t worry that’s a normal behavior ! The system’s one’s doing the same thing ! I just didn’t figured out how to do « OK » when it sigabort sry, I will post a msg on header of print. Sorry
