### ISSUE TITLE
strlcat et split sigabort

### ISSUE THREAD

**Issue by Morgadegit** [SimplySka/libft-war-machine-v2019#4]
Salut !

Déjà merci de nous avoir mis ce testeur à disposition, il est vraiment très pratique.

Cependant, y'a un problème avec strlcat et split : Le test 7 pour strlcat ne donne pas deux string mais une série de r sans \0 à la fin et une string. Pour split je sais pas quel est le problème exactement, le testeur donne des sigabort mais quand on test manuellement avec le main.c, tout se passe bien.

Voilà, merci encore pour ton aide !

**Comment by SimplySka** [comment]
Yo,
Pour strlcat, il faut empêcher le sigabort dans ta fonction : quand tu fais le strlen de ta destination, il ne faut pas que tu dépasse dstsize, le test est fait pour ça.
Pour le split, tu dois foirer tes mallocs, vient me chercher si tu galères^^
(Le testeur test avec les flags -g3 -fsanitize=address expres pour tester les sigabort si tu as des malloc mal foutu)
GL
