### ISSUE TITLE
bonus files are not compiled

### ISSUE THREAD

**Issue by TheoVideira** [SimplySka/libft-war-machine-v2019#7]
When i check compiling trace in deepthought, all my bonus files are missing. It seems that you don't use the bonus rule in makefiles. Is this intended and i should redeclare bonus functions that i want to use again ?

**Comment by SimplySka** [comment]
The program doesn't use makefile at all, it just checking files by files. Your problem is because i pushed new version where bonus files named are without _bonus.

**Comment by TheoVideira** [comment]
i don't understand, my files are named without _bonus. I think when you check file by file, you are compiling with libft.a but libft.a doesn't contain bonus functions. I may have not understand what you previously said so i give you a link to my repo in case of you see something wrong in it : https://github.com/TheoVideira/libft.git

**Comment by SimplySka** [comment]
I don't use makefile at all when checking file by file, that's not the issue, i'll check

**Comment by SimplySka** [comment]
It works for me, maybe you should pull last version ? don't know
[https://www.noelshack.com/2019-42-6-1571505174-capture-d-ecran-2019-10-19-a-19-12-02.png](url)

**Comment by TheoVideira** [comment]
i have the same result as you. the problem is if you check the deepthought at ft_lst_addback there is a linker error for an unknown reference to ft_lstlast, even though i have included libft.h in ft_lstadd_back.c

**Comment by SimplySka** [comment]
That's a depencie problem, because it don't use makefile to compile but it could work if your function is on your libft.a

**Comment by TheoVideira** [comment]
ok that's all i wanted to know, thank you, sorry to bother you
